/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qlnhanvien.view;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import qlnhanvien.controller.PhongBan_controller;

/**
 *
 * @author nhatnguyen
 */
public class Department_panel extends javax.swing.JPanel {

    PhongBan_controller ctr = new PhongBan_controller();
    DefaultTableModel model;

    int flag = 0;

    public Department_panel() {

        initComponents();
        EnableECRUD();
        DataTable();
    }

    public final void DataTable() {
        String[] columns = {"Mã phòng ban", "Tên phòng ban", "Địa chỉ", "Số ĐT", "Trạng thái"};
        model = new DefaultTableModel();
        model.setColumnIdentifiers(columns);
        tblPhongBan.setModel(model);
        String mapb = "";
        String tenpb = "";
        String diachi = "";
        String sodtpb = "";
        String trangthai = "";

        try {
            int dem1 = 0, dem2 = 0;
            for (int i = 0; i < ctr.getDataTable().size(); i++) {

                mapb = ctr.getDataTable().get(i).getMapb();
                tenpb = ctr.getDataTable().get(i).getTenpb();
                diachi = ctr.getDataTable().get(i).getDiachi();
                sodtpb = ctr.getDataTable().get(i).getSodtpb();

                switch (String.valueOf(ctr.getDataTable().get(i).getTrangthai())) {
                    case "1":
                        trangthai = "Active";
                        dem1++;
                        break;
                    case "0":
                        trangthai = "Disactive";
                        dem2++;
                        break;

                }
                model.addRow(new Object[]{
                    mapb, tenpb, diachi, sodtpb, trangthai
                });
            }
            txtTotalActive.setText(String.valueOf(dem1));
            txtTotalDisactive.setText(String.valueOf(dem2));
        } catch (Exception e) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, e);
        }
    }

    public final void EnableECRUD() {
        btnSave.setEnabled(false);
        btnCancel.setEnabled(false);

        btnAdd.setEnabled(true);
        btnUpdate.setEnabled(true);
        btnDelete.setEnabled(true);

    }

    public void DisableECRUD() {
        btnSave.setEnabled(true);
        btnCancel.setEnabled(true);

        btnAdd.setEnabled(false);
        btnUpdate.setEnabled(false);
        btnDelete.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPhongBan = new javax.swing.JTable();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtMaPB = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtTenPB = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtDiaChiPB = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtSodtPB = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        chbTrangThai = new javax.swing.JCheckBox();
        txtTotalActive = new javax.swing.JTextField();
        txtTotalDisactive = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setPreferredSize(new java.awt.Dimension(640, 460));

        btnAdd.setBackground(new java.awt.Color(0, 102, 255));
        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icadd.png"))); // NOI18N
        btnAdd.setText("Thêm");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnUpdate.setBackground(new java.awt.Color(0, 102, 102));
        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icreload.png"))); // NOI18N
        btnUpdate.setText("Sửa");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(255, 0, 0));
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icdelete.png"))); // NOI18N
        btnDelete.setText("Xóa");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        tblPhongBan.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tblPhongBan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblPhongBan.setRowHeight(30);
        tblPhongBan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPhongBanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPhongBan);

        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icsave.png"))); // NOI18N
        btnSave.setText("Lưu");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iccancel.png"))); // NOI18N
        btnCancel.setText("Hủy");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        jLabel10.setText("Mã phòng ban:");

        jLabel11.setText("Tên phòng ban:");

        jLabel12.setText("Địa chỉ:");

        jLabel13.setText("Số ĐT:");

        jLabel14.setText("Trạng thái:");

        chbTrangThai.setText("Còn hoạt động");

        jLabel8.setText("Số phòng ban hiện có:");

        jLabel9.setText("Số phòng ban dừng hoạt động:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUpdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancel))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel12)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtDiaChiPB, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                    .addComponent(txtTenPB, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chbTrangThai, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTotalActive, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotalDisactive, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaPB, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSodtPB))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAdd)
                        .addComponent(btnUpdate)
                        .addComponent(btnDelete))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnSave)
                        .addComponent(btnCancel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtMaPB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txtTenPB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDiaChiPB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSodtPB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chbTrangThai)
                            .addComponent(jLabel14))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTotalActive, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(txtTotalDisactive, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblPhongBanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPhongBanMouseClicked
        int row = tblPhongBan.getSelectedRow();
        txtMaPB.setText(tblPhongBan.getValueAt(row, 0).toString());
        txtTenPB.setText(tblPhongBan.getValueAt(row, 1).toString());
        txtDiaChiPB.setText(tblPhongBan.getValueAt(row, 2).toString());
        txtSodtPB.setText(tblPhongBan.getValueAt(row, 3).toString());
        if (tblPhongBan.getValueAt(row, 4).toString().trim().equals("Active")) {
            chbTrangThai.setSelected(true);
        } else {
            chbTrangThai.setSelected(false);
        }
    }//GEN-LAST:event_tblPhongBanMouseClicked

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        flag = 1;
        DisableECRUD();
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        flag = 2;
        DisableECRUD();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        String mapb = txtMaPB.getText();
        String tenpb = txtTenPB.getText();
        int dialogButton = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn xóa \"" + tenpb + "\" khỏi danh sách không?", "Xác nhận", dialogButton);

        if (dialogResult == JOptionPane.YES_NO_OPTION) {
            int rowDeleted = ctr.get_Delete_PhongBan(mapb);
            if (rowDeleted > 0) {
                JOptionPane.showMessageDialog(this, "Xóa nhân viên thành công");
                DataTable();
            } else {
                JOptionPane.showMessageDialog(this, "Xóa nhân viên thất bại");
            }
        }

    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        String mapb = txtMaPB.getText().trim();
        String tenpb = txtTenPB.getText();
        String diachi = txtDiaChiPB.getText();
        String sodtpb = txtSodtPB.getText();
        int trangthai;
        if (chbTrangThai.isSelected()) {
            trangthai = 1;
        } else {
            trangthai = 0;
        }

        if (mapb.equals("")) {
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập đủ thông tin, nhập lại!");
        } else if (tenpb.equals("")) {
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập đủ thông tin, nhập lại!");
        } else if (diachi.equals("")) {
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập đủ thông tin, nhập lại!");
        } else if (sodtpb.equals("")) {
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập đủ thông tin, nhập lại!");
        } else {
            switch (flag) {
                case 1:
                    int rowInserted = ctr.get_Insert_PhongBan(mapb, tenpb, diachi, sodtpb, trangthai);
                    if (rowInserted > 0) {
                        JOptionPane.showMessageDialog(this, "Thêm phòng ban thành công");
                        EnableECRUD();
                        DataTable();

                    } else {
                        JOptionPane.showMessageDialog(this, "Mã phòng ban đã tồn tại");
                    }
                    break;

                case 2:
                    int rowUpdated = ctr.get_Update_PhongBan(mapb, tenpb, diachi, sodtpb, trangthai);
                    if (rowUpdated > 0) {
                        JOptionPane.showMessageDialog(this, "Sửa phòng ban thành công");
                        EnableECRUD();
                        DataTable();

                    } else {
                        JOptionPane.showMessageDialog(this, "Sửa phòng ban thất bại!");
                    }
                    break;
            }
        }

    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        EnableECRUD();
    }//GEN-LAST:event_btnCancelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JCheckBox chbTrangThai;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPhongBan;
    private javax.swing.JTextField txtDiaChiPB;
    private javax.swing.JTextField txtMaPB;
    private javax.swing.JTextField txtSodtPB;
    private javax.swing.JTextField txtTenPB;
    private javax.swing.JTextField txtTotalActive;
    private javax.swing.JTextField txtTotalDisactive;
    // End of variables declaration//GEN-END:variables
}
