/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qlnhanvien.view;

import java.awt.Image;
import java.text.NumberFormat;
import java.util.Locale;
import javax.swing.ImageIcon;
import qlnhanvien.controller.NhanVien_Controller;

/**
 *
 * @author nhatnguyen
 */
public class DetailInfor_panel extends javax.swing.JPanel {

    /**
     * Creates new form DetailInfor_panel
     */
    public DetailInfor_panel() {
        initComponents();
        clearText();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtLookup = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lbImage = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lbMaNV = new javax.swing.JLabel();
        lbHoTen = new javax.swing.JLabel();
        lbNgaySinh = new javax.swing.JLabel();
        lbQueQuan = new javax.swing.JLabel();
        lbGioiTinh = new javax.swing.JLabel();
        lbSoDT = new javax.swing.JLabel();
        lbDanToc = new javax.swing.JLabel();
        lbPhongBan = new javax.swing.JLabel();
        lbChucVu = new javax.swing.JLabel();
        lbTrinhDo = new javax.swing.JLabel();
        lbHeSo = new javax.swing.JLabel();
        lbLuongCB = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        lbTongLuong = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Nhập mã nhân viên vào ô bên dưới");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Mã nhân viên:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Họ tên:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Ngày sinh:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Quê quán:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Số ĐT:");

        lbImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbImage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Giới tính:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Ảnh:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Dân tộc:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Trình độ:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Phòng ban:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Lương CB:");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Hệ số:");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Chức vụ:");

        lbMaNV.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbMaNV.setText("jLabel15");

        lbHoTen.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbHoTen.setText("jLabel16");

        lbNgaySinh.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbNgaySinh.setText("jLabel17");

        lbQueQuan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbQueQuan.setText("jLabel18");

        lbGioiTinh.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbGioiTinh.setText("jLabel19");

        lbSoDT.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbSoDT.setText("jLabel20");

        lbDanToc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbDanToc.setText("jLabel21");

        lbPhongBan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbPhongBan.setText("jLabel22");

        lbChucVu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbChucVu.setText("jLabel23");

        lbTrinhDo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbTrinhDo.setText("jLabel24");

        lbHeSo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbHeSo.setText("jLabel25");

        lbLuongCB.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbLuongCB.setText("jLabel26");

        jLabel15.setBackground(new java.awt.Color(102, 102, 102));
        jLabel15.setOpaque(true);

        jButton1.setText("Tra cứu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("Tổng lương:");

        lbTongLuong.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbTongLuong.setText("jLabel17");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtLookup, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jButton1)))
                .addGap(341, 341, 341))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel16))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbMaNV)
                            .addComponent(lbHoTen)
                            .addComponent(lbNgaySinh)
                            .addComponent(lbQueQuan)
                            .addComponent(lbGioiTinh)
                            .addComponent(lbSoDT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(148, 148, 148)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbHeSo)
                            .addComponent(lbLuongCB)
                            .addComponent(lbPhongBan)
                            .addComponent(lbChucVu)
                            .addComponent(lbTrinhDo)
                            .addComponent(lbDanToc))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 212, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbImage, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(134, 134, 134))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbTongLuong)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLookup, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(lbDanToc))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11)
                                    .addComponent(lbPhongBan))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel14)
                                    .addComponent(lbChucVu))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(lbTrinhDo)))
                            .addComponent(jLabel8)
                            .addComponent(lbImage, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(lbHeSo))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(lbLuongCB)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(lbMaNV))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(lbHoTen))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(lbNgaySinh))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(lbQueQuan))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(lbGioiTinh))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(lbSoDT))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(lbTongLuong))
                .addContainerGap(188, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public int Decimal(String hex) {
        String digits = "0123456789ABCDEF";
        hex = hex.toUpperCase();
        int val = 0;
        for (int i = 0; i < hex.length(); i++) {
            char c = hex.charAt(i);
            int d = digits.indexOf(c);
            val = 16 * val + d;
        }
        return val;
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        NhanVien_Controller nv = new NhanVien_Controller();
        String tk_nv = txtLookup.getText().trim();
        for (int i = 0; i < nv.Lookup(tk_nv).size(); i++) {
            lbMaNV.setText(nv.Lookup(tk_nv).get(i).getManv());
            lbHoTen.setText(nv.Lookup(tk_nv).get(i).getHoten());
            lbGioiTinh.setText(nv.Lookup(tk_nv).get(i).getGioitinh());
            lbChucVu.setText(nv.Lookup(tk_nv).get(i).getMacv());
            lbDanToc.setText(nv.Lookup(tk_nv).get(i).getDantoc());
            lbNgaySinh.setText(nv.Lookup(tk_nv).get(i).getNgaysinh());
            lbHeSo.setText(String.valueOf(nv.Lookup(tk_nv).get(i).getHeso()));
            lbImage.setText(nv.Lookup(tk_nv).get(i).getImage());
            lbLuongCB.setText(String.valueOf(nv.Lookup(tk_nv).get(i).getLuongcb()));
            lbPhongBan.setText(nv.Lookup(tk_nv).get(i).getMapb());
            lbQueQuan.setText(nv.Lookup(tk_nv).get(i).getQuequan());
            lbSoDT.setText(nv.Lookup(tk_nv).get(i).getSodt());
            lbTrinhDo.setText(nv.Lookup(tk_nv).get(i).getMatdhv());
//            String hex =String.format("%.f",nv.Lookup(tk_nv).get(i).getHeso()*nv.Lookup(tk_nv).get(i).getLuongcb());
            NumberFormat nf = NumberFormat.getInstance(new Locale("en", "US"));
            String val = nf.format(nv.Lookup(tk_nv).get(i).getHeso()*nv.Lookup(tk_nv).get(i).getLuongcb());
            lbTongLuong.setText(val + " VNĐ");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    public void clearText() {
        lbMaNV.setText("");
        lbHoTen.setText("");
        lbGioiTinh.setText("");
        lbChucVu.setText("");
        lbDanToc.setText("");
        lbHeSo.setText("");
        lbImage.setText("");
        lbLuongCB.setText("");
        lbPhongBan.setText("");
        lbQueQuan.setText("");
        lbSoDT.setText("");
        lbTrinhDo.setText("");
        lbNgaySinh.setText("");
        lbTongLuong.setText("");
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lbChucVu;
    private javax.swing.JLabel lbDanToc;
    private javax.swing.JLabel lbGioiTinh;
    private javax.swing.JLabel lbHeSo;
    private javax.swing.JLabel lbHoTen;
    private javax.swing.JLabel lbImage;
    private javax.swing.JLabel lbLuongCB;
    private javax.swing.JLabel lbMaNV;
    private javax.swing.JLabel lbNgaySinh;
    private javax.swing.JLabel lbPhongBan;
    private javax.swing.JLabel lbQueQuan;
    private javax.swing.JLabel lbSoDT;
    private javax.swing.JLabel lbTongLuong;
    private javax.swing.JLabel lbTrinhDo;
    private javax.swing.JTextField txtLookup;
    // End of variables declaration//GEN-END:variables
}
