/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qlnhanvien.view;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JDesktopPane;
import javax.swing.JInternalFrame;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;

/**
 *
 * @author LongLD
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form giaoDienChinh
     */
    public Main() {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        hinhnen = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        mn_Option = new javax.swing.JMenu(){};
        mnItem_Print = new javax.swing.JMenuItem();
        mnItem_Exit = new javax.swing.JMenuItem();
        mn_Employee = new javax.swing.JMenu();
        mnItem_AddEmployee = new javax.swing.JMenuItem();
        mnItem_DeleteEmployee = new javax.swing.JMenuItem();
        mnItem_UpdateEmployee = new javax.swing.JMenuItem();
        mn_SearchEmployee = new javax.swing.JMenu();
        mnItem_SearchEmployee = new javax.swing.JMenuItem();
        mn_ListEmployee = new javax.swing.JMenu();
        mnItem_ListAllEmployee = new javax.swing.JMenuItem();
        mnItem_ListEmployeeDepartment = new javax.swing.JMenuItem();
        mn_Logout = new javax.swing.JMenu();

        jMenuItem7.setText("jMenuItem7");

        jMenu4.setText("jMenu4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lý nhân viên");

        hinhnen.setBackground(new java.awt.Color(153, 153, 153));
        hinhnen.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 153, 153)));

        javax.swing.GroupLayout hinhnenLayout = new javax.swing.GroupLayout(hinhnen);
        hinhnen.setLayout(hinhnenLayout);
        hinhnenLayout.setHorizontalGroup(
            hinhnenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1184, Short.MAX_VALUE)
        );
        hinhnenLayout.setVerticalGroup(
            hinhnenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 648, Short.MAX_VALUE)
        );

        jMenuBar1.setBackground(new java.awt.Color(247, 247, 247));
        jMenuBar1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenuBar1.setPreferredSize(new java.awt.Dimension(318, 30));

        mn_Option.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        mn_Option.setText("Tùy chọn");
        mn_Option.setFocusable(false);
        mn_Option.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        mnItem_Print.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        mnItem_Print.setText("Print");
        mnItem_Print.setPreferredSize(new java.awt.Dimension(240, 40));
        mn_Option.add(mnItem_Print);

        mnItem_Exit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        mnItem_Exit.setText("Exit");
        mnItem_Exit.setPreferredSize(new java.awt.Dimension(240, 40));
        mn_Option.add(mnItem_Exit);

        jMenuBar1.add(mn_Option);

        mn_Employee.setText("Nhân viên");
        mn_Employee.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        mnItem_AddEmployee.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        mnItem_AddEmployee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icadd.png"))); // NOI18N
        mnItem_AddEmployee.setText("Thêm nhân viên");
        mnItem_AddEmployee.setPreferredSize(new java.awt.Dimension(240, 40));
        mnItem_AddEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnItem_AddEmployeeActionPerformed(evt);
            }
        });
        mn_Employee.add(mnItem_AddEmployee);

        mnItem_DeleteEmployee.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        mnItem_DeleteEmployee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icdelete.png"))); // NOI18N
        mnItem_DeleteEmployee.setText("Xóa nhân viên");
        mnItem_DeleteEmployee.setPreferredSize(new java.awt.Dimension(240, 40));
        mnItem_DeleteEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnItem_DeleteEmployeeActionPerformed(evt);
            }
        });
        mn_Employee.add(mnItem_DeleteEmployee);

        mnItem_UpdateEmployee.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        mnItem_UpdateEmployee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icedit.png"))); // NOI18N
        mnItem_UpdateEmployee.setText("Sửa thông tin NV");
        mnItem_UpdateEmployee.setPreferredSize(new java.awt.Dimension(240, 40));
        mnItem_UpdateEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnItem_UpdateEmployeeActionPerformed(evt);
            }
        });
        mn_Employee.add(mnItem_UpdateEmployee);

        jMenuBar1.add(mn_Employee);

        mn_SearchEmployee.setText("Tìm kiếm");
        mn_SearchEmployee.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        mnItem_SearchEmployee.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        mnItem_SearchEmployee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icsearch.png"))); // NOI18N
        mnItem_SearchEmployee.setText("Tìm nhân viên");
        mnItem_SearchEmployee.setPreferredSize(new java.awt.Dimension(240, 40));
        mn_SearchEmployee.add(mnItem_SearchEmployee);

        jMenuBar1.add(mn_SearchEmployee);

        mn_ListEmployee.setText("Danh sách nhân viên");
        mn_ListEmployee.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        mnItem_ListAllEmployee.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        mnItem_ListAllEmployee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iclist.png"))); // NOI18N
        mnItem_ListAllEmployee.setLabel("Danh sách nhân viên");
        mnItem_ListAllEmployee.setPreferredSize(new java.awt.Dimension(240, 40));
        mn_ListEmployee.add(mnItem_ListAllEmployee);

        mnItem_ListEmployeeDepartment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iclist.png"))); // NOI18N
        mnItem_ListEmployeeDepartment.setText("Danh sách theo bộ phận");
        mnItem_ListEmployeeDepartment.setPreferredSize(new java.awt.Dimension(240, 40));
        mn_ListEmployee.add(mnItem_ListEmployeeDepartment);

        jMenuBar1.add(mn_ListEmployee);

        mn_Logout.setText("Đăng xuất");
        mn_Logout.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mn_Logout.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        mn_Logout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        mn_Logout.setName("mnLogout"); // NOI18N
        jMenuBar1.add(mn_Logout);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(hinhnen)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(hinhnen))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnItem_DeleteEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnItem_DeleteEmployeeActionPerformed
        // TODO add your handling code here:
        for (JInternalFrame removeMember : hinhnen.getAllFrames()) {
            removeMember.dispose();
        }
        RemoveEmployee rem = new RemoveEmployee();
        rem.setTitle("Add new Member");
        rem.setLocation(this.getWidth() / 2 - rem.getWidth() / 2, (this.getHeight() - 20) / 2 - rem.getHeight() / 2 - 20);
        hinhnen.add(rem);
        rem.setVisible(true);
    }//GEN-LAST:event_mnItem_DeleteEmployeeActionPerformed

    private void mnItem_UpdateEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnItem_UpdateEmployeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnItem_UpdateEmployeeActionPerformed

    private void mnItem_AddEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnItem_AddEmployeeActionPerformed
        // TODO add your handling code here:
//        for (JInternalFrame addMember : hinhnen.getAllFrames()) {
//            addMember.dispose();
//        }
//        AddMember addm = new AddMember();
//        addm.setLocation(this.getWidth() / 2 - addm.getWidth() / 2, (this.getHeight() - 20) / 2 - addm.getHeight() / 2 - 20);
//        hinhnen.add(addm);
//        addm.setVisible(true);
//        
        for (JInternalFrame add : hinhnen.getAllFrames()) {
            add.dispose();
        }
        add a = new add();
        a.setLocation(this.getWidth() / 2 - a.getWidth() / 2, (this.getHeight() - 20) / 2 - a.getHeight() / 2 - 20);
        hinhnen.add(a);
        a.setVisible(true);
    }//GEN-LAST:event_mnItem_AddEmployeeActionPerformed

//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                Main gdc =new Main();
//                gdc.setLocationRelativeTo(null);
//                gdc.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane hinhnen;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem mnItem_AddEmployee;
    private javax.swing.JMenuItem mnItem_DeleteEmployee;
    private javax.swing.JMenuItem mnItem_Exit;
    private javax.swing.JMenuItem mnItem_ListAllEmployee;
    private javax.swing.JMenuItem mnItem_ListEmployeeDepartment;
    private javax.swing.JMenuItem mnItem_Print;
    private javax.swing.JMenuItem mnItem_SearchEmployee;
    private javax.swing.JMenuItem mnItem_UpdateEmployee;
    private javax.swing.JMenu mn_Employee;
    private javax.swing.JMenu mn_ListEmployee;
    private javax.swing.JMenu mn_Logout;
    private javax.swing.JMenu mn_Option;
    private javax.swing.JMenu mn_SearchEmployee;
    // End of variables declaration//GEN-END:variables
}
