/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qlnhanvien.view;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import qlnhanvien.controller.ChucVu_Controller;
import qlnhanvien.model.Chucvu_model;

/**
 *
 * @author nhatnguyen
 */
public class Position_panel extends javax.swing.JPanel {

    ChucVu_Controller ctr = new ChucVu_Controller();
    DefaultTableModel model;
    int flag = 0;

    public Position_panel() {
        initComponents();
        EnableECRUD();
        DataTable();
        Authen();
    }

    public void Authen() {
        if (Login.role == 1) {
            btnAdd.setEnabled(false);
            btnUpdate.setEnabled(false);
            btnDelete.setEnabled(false);
        }
    }

    public final void DataTable() {
        String[] columns = {"Mã chức vụ", "Tên chức vụ", "Trạng thái"};
        model = new DefaultTableModel();
        model.setColumnIdentifiers(columns);
        tblChucVu.setModel(model);
        String macv = "";
        String tencv = "";
        String trangthai = "";

        try {
            int dem1 = 0, dem2 = 0;
            for (int i = 0; i < ctr.getDataTable().size(); i++) {

                macv = ctr.getDataTable().get(i).getMacv();
                tencv = ctr.getDataTable().get(i).getTencv();

                switch (String.valueOf(ctr.getDataTable().get(i).getTrangthai())) {
                    case "1":
                        trangthai = "Active";
                        dem1++;
                        break;
                    case "0":
                        trangthai = "Disactive";
                        dem2++;
                        break;

                }
                model.addRow(new Object[]{
                    macv, tencv, trangthai
                });
            }
        } catch (Exception e) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, e);
        }
    }

    public final void EnableECRUD() {
        btnSave.setEnabled(false);
        btnCancel.setEnabled(false);

        btnAdd.setEnabled(true);
        btnUpdate.setEnabled(true);
        btnDelete.setEnabled(true);

    }

    public void DisableECRUD() {
        btnSave.setEnabled(true);
        btnCancel.setEnabled(true);

        btnAdd.setEnabled(false);
        btnUpdate.setEnabled(false);
        btnDelete.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblChucVu = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        chbTrangThai = new javax.swing.JCheckBox();
        btnCancel = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtMaCV = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtTenCV = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnUpdate.setBackground(new java.awt.Color(0, 102, 102));
        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icreload.png"))); // NOI18N
        btnUpdate.setText("Sửa");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(255, 0, 0));
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icdelete.png"))); // NOI18N
        btnDelete.setText("Xóa");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        tblChucVu.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tblChucVu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblChucVu.setFillsViewportHeight(true);
        tblChucVu.setRowHeight(30);
        tblChucVu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblChucVuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblChucVu);

        jLabel14.setText("Trạng thái:");

        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icsave.png"))); // NOI18N
        btnSave.setText("Lưu");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        chbTrangThai.setText("Còn hoạt động");

        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iccancel.png"))); // NOI18N
        btnCancel.setText("Hủy");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        jLabel10.setText("Mã chức vụ:");

        jLabel11.setText("Tên chức vụ:");

        btnAdd.setBackground(new java.awt.Color(0, 102, 255));
        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icadd.png"))); // NOI18N
        btnAdd.setText("Thêm");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUpdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancel))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 509, Short.MAX_VALUE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel14))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chbTrangThai)
                    .addComponent(txtTenCV, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaCV, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(176, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAdd)
                        .addComponent(btnUpdate)
                        .addComponent(btnDelete))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnSave)
                        .addComponent(btnCancel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtMaCV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txtTenCV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chbTrangThai)
                            .addComponent(jLabel14))
                        .addContainerGap())
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        flag = 2;
        DisableECRUD();
        txtMaCV.setEnabled(false);
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        String macv = txtMaCV.getText();
        String tencv = txtTenCV.getText();
        int dialogButton = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn xóa \"" + tencv + "\" khỏi danh sách không?", "Xác nhận", dialogButton);

        if (dialogResult == JOptionPane.YES_NO_OPTION) {
            int rowDeleted = ctr.get_Delete_ChucVu(macv);
            if (rowDeleted > 0) {
                JOptionPane.showMessageDialog(this, "Xóa chức vụ thành công");
                DataTable();
            } else {
                JOptionPane.showMessageDialog(this, "Xóa chức vụ thất bại");
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void tblChucVuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblChucVuMouseClicked
        int row = tblChucVu.getSelectedRow();
        txtMaCV.setText(tblChucVu.getValueAt(row, 0).toString());
        txtTenCV.setText(tblChucVu.getValueAt(row, 1).toString());
        if (tblChucVu.getValueAt(row, 2).toString().trim().equals("Active")) {
            chbTrangThai.setSelected(true);
        } else {
            chbTrangThai.setSelected(false);
        }
    }//GEN-LAST:event_tblChucVuMouseClicked

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        String macv = txtMaCV.getText().trim();
        String tencv = txtTenCV.getText();
        int trangthai;
        if (chbTrangThai.isSelected()) {
            trangthai = 1;
        } else {
            trangthai = 0;
        }

        if (macv.equals("")) {
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập đủ thông tin, nhập lại!");
        } else if (tencv.equals("")) {
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập đủ thông tin, nhập lại!");
        } else {
            switch (flag) {
                case 1:
                    int rowInserted = ctr.get_Insert_ChucVu(macv, tencv, trangthai);
                    if (rowInserted > 0) {
                        JOptionPane.showMessageDialog(this, "Thêm chức vụ thành công");
                        EnableECRUD();
                        DataTable();

                    } else {
                        JOptionPane.showMessageDialog(this, "Mã chức vụ đã tồn tại");
                    }
                    break;

                case 2:
                    int rowUpdated = ctr.get_Update_ChucVu(macv, tencv, trangthai);
                    if (rowUpdated > 0) {
                        JOptionPane.showMessageDialog(this, "Sửa chức vụ thành công");
                        EnableECRUD();
                        DataTable();

                    } else {
                        JOptionPane.showMessageDialog(this, "Sửa chức vụ thất bại!");
                    }
                    break;
            }
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        EnableECRUD();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        flag = 1;
        DisableECRUD();
    }//GEN-LAST:event_btnAddActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JCheckBox chbTrangThai;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblChucVu;
    private javax.swing.JTextField txtMaCV;
    private javax.swing.JTextField txtTenCV;
    // End of variables declaration//GEN-END:variables
}
